# Generated by Django 2.2.4 on 2020-05-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('total_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('product_image', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
