# Generated by Django 2.2.4 on 2020-05-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_name',
            new_name='product',
        ),
    ]
