# Generated by Django 2.2.4 on 2020-05-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200524_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
