# Generated by Django 2.2.4 on 2020-05-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
