# Generated by Django 2.2.4 on 2020-05-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cart_product_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
