# Generated by Django 2.2.4 on 2020-05-28 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0018_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('apartmentno', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=6)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_amount', models.IntegerField(default=0)),
                ('is_refunded', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='shop.Cart')),
                ('supplier', models.ManyToManyField(to='shop.Supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('apartmentno', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=6)),
                ('category', models.CharField(choices=[('1', 'Category1'), ('2', 'Category2')], max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
