# Generated by Django 2.2.4 on 2020-06-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200602_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_name',
            new_name='supplier_details',
        ),
    ]
