# Generated by Django 3.0.4 on 2020-06-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200602_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='number',
        ),
    ]
