# Generated by Django 3.0.2 on 2020-06-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
